Movie/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include('movie_app.urls')),
    path('accounts/', include('accounts.urls')),
]

movie_app/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


# Create your models here.
class Person(models.Model):
    first_name = models.CharField(max_length=123)
    last_name = models.CharField(max_length=123)
    year = models.IntegerField()

    def get_detail_url(self):
        return reverse('detail_person', kwargs={'id':self.id})

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Genre(models.Model):
    name = models.CharField(max_length=123)


    def get_detail_url(self):
        return reverse('detail_genre', kwargs={'id':self.id})

    def __str__(self):
        return self.name


class Producer(models.Model):
    name = models.CharField(max_length=123)
    city = models.CharField(max_length=123)
    year = models.IntegerField()

    def get_detail_url(self):
        return reverse('detail_producer', kwargs={'id':self.id})

    def __str__(self):
        return f"{self.name} {self.city}"


class Movie(models.Model):
    title = models.CharField(max_length=123)
    year = models.IntegerField()
    director = models.ForeignKey(Person, on_delete=models.CASCADE)
    producer = models.ForeignKey(Producer, on_delete=models.CASCADE)
    genre = models.ManyToManyField(Genre)

    def get_detail_url(self):
        return reverse('detail_movie', kwargs={'id':self.id})

    def __str__(self):
        return self.title

class Comment(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    date = models.DateTimeField(auto_now=True)

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <title>Document</title>
</head>
<body>
<h5>{{ date }}</h5>
{% include 'user_panel.html' %}
<ul class="nav">
    <li class="nav"><a href="{% url 'add_genre' %}">dodaj Gatunek</a> </li>
    <li class="nav"><a href="{% url 'add_movie' %}">dodaj Film</a> </li>
    <li class="nav"><a href="{% url 'add_producer' %}">dodaj producenta</a> </li>
    <li class="nav"><a href="{% url 'add_person' %}">dodaj osobe</a> </li>
    <li class="nav"><a href="{% url 'list_person' %}">Osoby</a> </li>
    <li class="nav"><a href="{% url 'list_genre' %}">Gatunki</a> </li>
    <li class="nav"><a href="{% url 'list_movie' %}">filmy</a> </li>
    <li class="nav"><a href="{% url 'user_list' %}">Uzytkownicy</a> </li>

</ul>
{% block content %}
    Witam !!!
{% endblock %}
{% block jscript %}
{% endblock %}
</body>
</html>

templates/form2.html
{% extends 'base.html' %}
{% block content %}
    <form method="post">
    {% csrf_token %}
    <table>
        <thead>
            <tr><th> nazwa </th><th>input</th><th>errors</th></tr>
        </thead>
        <tbody>

        {% for field in form %}
        <tr>
            <td>{{ field.name }}</td>
            <td>{{ field }}</td>
            <td>{% for error in field.errors %}{{ error }}{% endfor %}</td>
        </tr>
        {% endfor %}
        <tr><td colspan="3">{% for error in form.non_field_errors %}{{ error }}{% endfor %}</td></tr>
        </tbody>
    </table>
    <input type="submit">
    </form>
{% endblock %}

templates/genre_detail.html
{% extends 'base.html' %}
{% block content %}
    {{ genre }}
{% endblock %}

templates/list.html
<ul id="lista">
    {% for obj in objects %}
        <li><a href="{{ obj.get_detail_url }}"> {{ obj }}</a></li>
    {% endfor %}
</ul>

templates/list_view.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <form>
        <input type="text" name="name" id="genre_name" autocomplete="off">
    </form>
    {% include 'list.html' with objects=genres %}
{% endblock %}
{% block jscript %}
    <script src="{% static 'JS/genre_search.js' %}"></script>
{% endblock %}

templates/movie_detail.html
{% extends 'base.html' %}
{% block content %}
    <ul>
        <li>
            tytuł - {{ movie.title }}
        </li>
        <li>
            rok produkcji - {{ movie.year }}
        </li>
        <li>
            reżyser - {{ movie.director }}
        </li>
        <li>
            garunki - {% for genre in movie.genre.all %} {{ genre }} {% endfor %}
        </li>
        <li>
            wytwornia - {{ movie.producer }}
        </li>
    </ul>
    <a href="{% url 'add_comment' movie.id %}">Dodaj komentarz</a>
    <h1>comments:</h1>
    <ul>
        {% for comment in movie.comment_set.all %}
            <li><p>{{ comment.text }}</p><small>{{ comment.date }} {{ comment.creator }}</small></li>
        {% endfor %}
    </ul>
{% endblock %}

templates/movie_list.html
{% extends 'base.html' %}
{% block content %}
    {% include 'list.html' with objects=movies %}
{% endblock %}

templates/person_detail.html
{% extends 'base.html' %}
{% block content %}
{{ person }}
    {{ person.year }}
{% endblock %}

templates/person_list.html
{% extends 'base.html' %}
{% block content %}
    <form>
    {{ form.as_p }}
    <input type="submit">
    </form>
    {% include 'list.html' with objects=persons %}
{% endblock %}

templates/producer_detail.html
{% extends 'base.html' %}
{% block content %}
    {{ producer }}
    {{ object }}
{% endblock %}

templates/producer_list.html
{% extends 'base.html' %}
{% block content %}
    {% include 'list.html' with objects=object_list %}
{% endblock %}

templates/user_panel.html
<p>
{% if user.is_authenticated %}

    Witaj {{ user.username }}<br>
    <a href="{% url 'logout' %}">Wyloguj</a>

{% else %}
    <a href="{% url 'login' %}">Zaloguj</a>
    <a href="{% url 'register' %}">rejestracja</a>
{% endif %}
 </p>